site_name: Projet de documentation - Rafael Olivieri
site_description: Ce projet à pour objectif de documenter mon travail.
site_author: Olivieri Rafael
site_url: https://rvf3.github.io/mkdocs-docs/

# Configuration du dépôt
repo_name: rvf3/mkdocs-docs
repo_url: https://github.com/rvf3/mkdocs-docs

# Configuration du thème   
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
      scheme : slate
  font:
    text: Roboto
    code: Roboto Mono

# Extensions Markdown
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Configuration de la navigation
nav:
  - Accueil: index.md
  - Choix technologie: choix-techno.md
  - Réalisation de ce projet: rea-proj.md

# Configuration supplémentaire
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rvf3
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/votre-utilisateur

copyright: Copyright &copy; 2023 Olivieri Rafael
